filter_len_11:
	cd ..; make filter_len_11

mkd:
	cd ..; make mkd

triplets:
	cd ..; make triplets

convert_fragments:
	cd ..; make convert_fragments

write_chains:
	cd ..; make write_chains

check_chains:
	cd ..; make check_chains

get_fasta:
	cd ..; make get_fasta

